/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-09 08:49:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.ajaxuser;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import semi.dk.user.model.dto.UserDto;
import java.util.List;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("semi.dk.user.model.dto.UserDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".grid-wrap{\r\n");
      out.write("	display:grid;\r\n");
      out.write("	grid-template-columns:  auto auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h2>ajax test</h2>\r\n");
      out.write("	");
 List<UserDto> volist = (List<UserDto>)request.getAttribute("ulist"); 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<form>\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>날짜</td>\r\n");
      out.write("				<td>번호</td>\r\n");
      out.write("				<td>등록아이디</td>\r\n");
      out.write("				<td>가격</td>\r\n");
      out.write("				<td>품목분류</td>\r\n");
      out.write("				<td>자산</td>\r\n");
      out.write("				<td>이름</td>\r\n");
      out.write("				<td>설명</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ulist.insertDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ulist.Mno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ulist.Mid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ulist.Mprice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ulist.Category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ulist.CashCard}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ulist.Mname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ulist.Descripion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">되돌아가기</a>\r\n");
      out.write("	</form>\r\n");
      out.write("	<form action=\"");
      out.print(request.getContextPath() );
      out.write("/user/main.main\" method=\"post\">	\r\n");
      out.write(" 		<table border=\"1\">\r\n");
      out.write("	 		<tr>\r\n");
      out.write("	 			<td colspan=\"2\">지출 정보 등록</td>\r\n");
      out.write("	 		</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>날짜</td>\r\n");
      out.write("				<td><input type=\"date\" name=\"insertDate\" id=\"currentDate\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("<!-- 		<tr>\r\n");
      out.write("				<td>등록번호</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"mno\"></td>\r\n");
      out.write("			</tr> -->\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>아이디</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"mid\" ></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>가격</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"mprice\" ></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>분류</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"category\" ></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>자산</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"cashCard\" ></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>이름</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"mname\" ></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>설명</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"descripion\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<button type=\"submit\" id=\"ajaxlist\">등록</button>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	/* document.getElementById('currentDate').value = new Date().toISOString().substring(0, 10); */\r\n");
      out.write("	/* document.getElementById('currentDate1').value = new Date().toISOString().substring(0, 10); */\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${\"#ajaxlist\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".click(ajaxListClickHandler);\r\n");
      out.write("	\r\n");
      out.write("	function ajaxListClickHandler() {\r\n");
      out.write("		console.log(\"ajaxlist click\");\r\n");
      out.write("		$.ajax ({\r\n");
      out.write("			url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ajax\"\r\n");
      out.write("			, type: \"post\"\r\n");
      out.write("			, success: ajaxListSuccess\r\n");
      out.write("			, dataType: \"json\"\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function ajaxListSuccess(result){\r\n");
      out.write("		if(result) {\r\n");
      out.write("			for(var i=0; i<result.ulist.length; i++){\r\n");
      out.write("				var dvo = result.ulist[i]; \r\n");
      out.write("				console.log(dvo.insertDate);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		displayDepartment(result.ulist);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function displayDepartment(ulist){\r\n");
      out.write("		htmlVal = \"<td>날짜</td><td>번호</td><td>등록아이디</td><td>가격</td><td>품목분류</td><td>자산</td>	<td>이름</td><td>설명</td>\";\r\n");
      out.write("		for(var i=0; i<ulit.length;i++){\r\n");
      out.write("			var dvo = ulist[i];\r\n");
      out.write("			htmlVal+= `\r\n");
      out.write("				<td>${dvo.insertDate}</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dvo.Mno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dvo.Mid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dvo.Mprice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dvo.Category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dvo.CashCard}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dvo.Mname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dvo.Descripion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("			`;\r\n");
      out.write("/* 			htmlVal +=\"<div>\"+dvo.insertDate+\"</div>\";\r\n");
      out.write("			htmlVal += \"<div>\"+dvo.Mno+\"</div>\";\r\n");
      out.write("			htmlVal += \"<div>\"+dvo.Mid+\"</div>\";\r\n");
      out.write("			htmlVal += \"<div>\"+dvo.Mprice+\"</div>\";\r\n");
      out.write("			htmlVal += \"<div>\"+dvo.Category+\"</div>\";\r\n");
      out.write("			htmlVal += \"<div>\"+dvo.CashCard+\"</div>\";\r\n");
      out.write("			htmlVal += \"<div>\"+dvo.Mname+\"</div>\";\r\n");
      out.write("			htmlVal += \"<div>\"+dvo.Descripion+\"</div>\"; */\r\n");
      out.write("		}\r\n");
      out.write("		$('.grid-wrap').html(htmlVal);	\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
